name: Auto-Update Feeds

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

# Add permissions for the workflow
permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify a concrete Python version

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install feedparser==6.0.10

      - name: Run update script
        run: python update_feeds.py

      - name: Commit changes
        run: |
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add index.html
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update feeds - $TIMESTAMP"
            git push

